name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "Havit"
          output_location: "bin/Publish/wwwroot"
          app_build_command: "dotnet publish -c Release -o bin/Publish"
          api_location: "Api"
          skip_app_build: false
        env:
          DOTNET_ROOT: /usr/share/dotnet
          
      # Add this if you want to handle the case when the token is missing
      - name: Handle Missing Token
        if: failure() && steps.builddeploy.outcome == 'failure'
        run: |
          if [[ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]]; then
            echo "::error::Azure Static Web Apps API token is missing. Please add it to your repository secrets."
            exit 1
          fi
